// src/frontend/pages/hero/History.svelte
<!-- svelte-ignore event_directive_deprecated -->
<!-- svelte-ignore a11y_no_static_element_interactions -->

<script lang="ts">
    import Fuse from "fuse.js";
    import Button from "../../components/ui/button.svelte";
    import Input from "../../components/ui/input.svelte";
    import type { HistoryRecord, Pagination } from "./types";

    type $$props = {
        history: HistoryRecord[];
        handleClickToHistory: (record: any) => void;
        pagination: Pagination;
        setPagination: (value: Pagination) => void;
        disabled: boolean;
    };

    let {
        history,
        handleClickToHistory,
        pagination,
        setPagination,
        disabled = false,
    }: $$props = $props();

    let hovered = $state(false);
    let inputValue = $state("");
    let filteredData: HistoryRecord[] = $state([]);
    let paginatedData: HistoryRecord[] = $state([]);
    let totalItems = $state(0);

    let fuse: Fuse<HistoryRecord> = $state();

    $effect(() => {
        fuse = new Fuse(history, {
            keys: ["query", "type"],
            threshold: 0.4,
            includeMatches: true,
        });
    });

    function onDataChange(inputValue: string) {
        filteredData = !inputValue ? history : fuse.search(inputValue).map(result => result.item);
        console.log(filteredData, inputValue);
        totalItems = filteredData.length;

        const start = pagination.cur * pagination.maxPerPage;
        const end = start + pagination.maxPerPage;
        paginatedData = filteredData.slice(start, end);
    }

    function handleSearch(e: Event) {
        inputValue = (e.target as HTMLInputElement).value;
        setPagination({
            ...pagination,
            cur: 0,
        });
    }

    function highlightText(text: string, highlight: string) {
        if (!highlight.trim()) return text;

        const regex = new RegExp(`(${highlight})`, "gi");
        const parts = text.split(regex);

        return parts
            .map((part, i) => {
                if (regex.test(part)) {
                    return `<span class="bg-blue-500 text-white">${part}</span>`;
                }
                return part;
            })
            .join("");
    }

    let debounceTimeout;

    function debounce(func, wait) {
        return function (...args) {
            clearTimeout(debounceTimeout);
            debounceTimeout = setTimeout(() => func.apply(this, args), wait);
        };
    }

    const debouncedOnDataChange = debounce(onDataChange, 300);

    $effect(() => {
        debouncedOnDataChange(inputValue);
    });
</script>

{#if history.length > 0}
    <div
        class="mt-6 bg-black p-2 relative"
        style="pointer-events: {disabled ? 'none' : 'all'}; cursor: {disabled ? 'wait' : ''}"
    >
        <div on:mouseenter={() => (hovered = true)} on:mouseleave={() => (hovered = false)}>
            {#if !hovered && inputValue.trim().length === 0}
                <h2 class="text-lg mb-1 mt-2">Search History</h2>
            {/if}

            {#if hovered || inputValue.trim().length > 0}
                <div>
                    <Input
                        autofocus
                        value={inputValue}
                        class="w-[10rem] h-10 px-2"
                        oninput={handleSearch}
                        placeholder="Search history..."
                    />
                </div>
            {/if}
        </div>

        <table class="w-full">
            <caption>A list of your recent searches.</caption>
            <thead>
                <tr>
                    <th class="">Query</th>
                    <th>Created at</th>
                    <th>Type</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {#each paginatedData as record (record.timestamp)}
                    <tr>
                        <td class="font-medium w-full">
                            {@html highlightText(record.query, inputValue)}
                        </td>
                        <td class="whitespace-nowrap max-sm:whitespace-normal">
                            {new Date(record.timestamp).toLocaleString("en-US", {
                                month: "short",
                                day: "2-digit",
                                hour: "2-digit",
                                minute: "2-digit",
                            })}
                        </td>
                        <td>
                            {@html highlightText(record.type, inputValue)}
                        </td>
                        <td>
                            <Button
                                onclick={() => handleClickToHistory(record)}
                                size="sm"
                                variant="outline"
                            >
                                Restore
                            </Button>
                        </td>
                    </tr>
                {/each}
            </tbody>
        </table>

        {#if Math.round(totalItems / pagination.maxPerPage)}
            <div class="space-x-2 flex justify-end align-middle my-2">
                <Button
                    variant="outline"
                    size="sm"
                    disabled={pagination.cur <= 0}
                    onclick={() => {
                        setPagination({
                            ...pagination,
                            cur: pagination.cur - 1,
                        });
                        onDataChange(inputValue);
                    }}
                >
                    Previous
                </Button>

                <span class="bold block ring-slate-500 p-1">
                    {pagination.cur + 1}/{Math.ceil(totalItems / pagination.maxPerPage) || 1}
                </span>

                <Button
                    variant="outline"
                    size="sm"
                    disabled={pagination.cur >= Math.ceil(totalItems / pagination.maxPerPage) - 1}
                    onclick={() => {
                        setPagination({
                            ...pagination,
                            cur: pagination.cur + 1,
                        });
                        onDataChange(inputValue);
                    }}
                >
                    Next
                </Button>
            </div>
        {/if}
    </div>
{/if}

<style>
    table {
        width: 100%;
    }

    th,
    td {
        padding: 0.5rem;
        text-align: left;
    }
</style>

// src/frontend/pages/hero/History.tsx
import Fuse from "fuse.js";
import React, { useEffect, useState } from "react";
import { useMemo } from "react";

import { Button } from "../../components/ui/button";
import {
    Table,
    TableBody,
    TableCaption,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from "../../components/ui/table";
import { Input } from "../../components/ui/input";
import { HistoryRecord, Pagination } from "./types";

// Highlight component for matching text
const Highlight = ({ text, highlight }: { text: string; highlight: string }) => {
    if (!highlight.trim()) {
        return <span>{text}</span>;
    }

    const regex = new RegExp(`(${highlight})`, "gi");
    const parts = text.split(regex);

    return (
        <span>
            {parts.map((part, i) =>
                regex.test(part) ? (
                    <span key={i} className="bg-blue-500 text-white">
                        {part}
                    </span>
                ) : (
                    <span key={i}>{part}</span>
                )
            )}
        </span>
    );
};

// Modified TableDemo component
const TableDemo = ({
    data,
    handleClickToHistory,
    pagination,
    searchTerm,
}: {
    data: HistoryRecord[];
    handleClickToHistory: (r: any) => void;
    pagination: Pagination;
    searchTerm: string;
}) => {
    const fuse = useMemo(
        () =>
            new Fuse(data, {
                keys: ["query", "type"],
                threshold: 0.4,
                includeMatches: true,
            }),
        [data]
    );

    const filteredData = useMemo(() => {
        if (!searchTerm) return data;
        return fuse.search(searchTerm).map(result => result.item);
    }, [fuse, searchTerm, data]);

    const paginatedData = filteredData.slice(
        pagination.cur * pagination.maxPerPage,
        (pagination.cur + 1) * pagination.maxPerPage
    );

    return (
        <Table>
            <TableCaption>A list of your recent searches.</TableCaption>
            <TableHeader>
                <TableRow>
                    <TableHead className="">Query</TableHead>
                    <TableHead>Created at</TableHead>
                    <TableHead>Type</TableHead>
                    <TableHead>Action</TableHead>
                </TableRow>
            </TableHeader>
            <TableBody>
                {paginatedData.map(record => (
                    <TableRow key={record.timestamp}>
                        <TableCell className="font-medium w-full">
                            <Highlight text={record.query} highlight={searchTerm} />
                        </TableCell>
                        <TableCell className="whitespace-nowrap max-sm:whitespace-normal">
                            {new Date(record.timestamp).toLocaleString("en-US", {
                                month: "short",
                                day: "2-digit",
                                hour: "2-digit",
                                minute: "2-digit",
                            })}
                        </TableCell>
                        <TableCell>
                            <Highlight text={record.type} highlight={searchTerm} />
                        </TableCell>
                        <TableCell>
                            <Button
                                onClick={() => handleClickToHistory(record)}
                                size="sm"
                                variant="outline">
                                Restore
                            </Button>
                        </TableCell>
                    </TableRow>
                ))}
            </TableBody>
        </Table>
    );
};

type HistoryProps = {
    history: HistoryRecord[];
    handleClickToHistory: (r: any) => void;
    pagination: Pagination;
    setPagination: React.Dispatch<React.SetStateAction<Pagination>>;
    disabled: boolean;
};

// Modified History component
const History = ({
    history,
    setPagination,
    pagination,
    handleClickToHistory,
    disabled,
}: HistoryProps) => {
    const [hovered, setHovered] = useState(false);
    const [inputValue, setInputValue] = useState("");

    // Update pagination when search results change
    useEffect(() => {
        setPagination(p => ({
            ...p,
            cur: 0,
            total: history.length,
        }));
    }, [inputValue, history.length, setPagination]);

    return (
        <>
            {history.length > 0 && (
                <div
                    className="mt-6 bg-black p-2 relative"
                    style={{
                        pointerEvents: disabled ? "none" : "all",
                        cursor: disabled ? "wait" : "",
                    }}>
                    <div
                        onMouseEnter={() => setHovered(true)}
                        onMouseLeave={() => setHovered(false)}>
                        {!hovered && inputValue.trim().length === 0 && (
                            <h2 className="text-lg mb-1 mt-2">Search History</h2>
                        )}
                        {(hovered || inputValue.trim().length > 0) && (
                            <div>
                                <Input
                                    autoFocus
                                    value={inputValue}
                                    className="w-[10rem] h-10"
                                    onChange={e => setInputValue(e.target.value)}
                                    placeholder="Search history..."
                                />
                            </div>
                        )}
                    </div>

                    <TableDemo
                        pagination={pagination}
                        handleClickToHistory={handleClickToHistory}
                        data={history}
                        searchTerm={inputValue}
                    />

                    {Boolean(Math.round(pagination.total / pagination.maxPerPage)) && (
                        <div className="space-x-2 flex justify-end align-middle my-2">
                            <Button
                                variant="outline"
                                size="sm"
                                disabled={pagination.cur <= 0}
                                onClick={() => {
                                    setPagination(p => ({
                                        ...p,
                                        cur: p.cur > 0 ? p.cur - 1 : p.cur,
                                    }));
                                }}>
                                Previous
                            </Button>

                            <span className="bold block ring-slate-500 p-1">
                                {pagination.cur + 1}/
                                {Math.round(pagination.total / pagination.maxPerPage) || 1}
                            </span>

                            <Button
                                variant="outline"
                                size="sm"
                                disabled={
                                    pagination.cur >=
                                    Math.ceil(pagination.total / pagination.maxPerPage) - 1
                                }
                                onClick={() => {
                                    setPagination(p => ({
                                        ...p,
                                        cur:
                                            p.cur >
                                            Math.round(pagination.total / pagination.maxPerPage)
                                                ? p.cur
                                                : p.cur + 1,
                                    }));
                                }}>
                                Next
                            </Button>
                        </div>
                    )}
                </div>
            )}
        </>
    );
};

export default History;
